name: Node.js CI

# when to trigger jobs
on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

# what should do
jobs:
  # this is a block, name could be any name
  build:
    # runs on what server
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
      # uses:
      # (1) from github repo
      # (2) `checkout` will download some-version of your code to github actions runner
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
          run_install: false
      # name: (1) any name (2)this like a for loop (3) could have `uses`, `with`
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      # run: run the command of our code
      - run: npm i
      - run: npm run build

  # this is also a block, name could be any name
  tests:
    # runs on what server
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
      # uses:
      # (1) from github repo
      # (2) `checkout` will download some-version of your code to github actions runner
      - name: Checkout
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 9
          run_install: false

      # name: (1) any name (2)this like a for loop (3) could have `uses`, `with`
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      # run: run the command of our code
      - run: npm i
      - run: npm run test
